/**
 * This file helps us dynamically buld our environment variables in to
 * Angular environment.ts files.
 */

const fs = require('fs');
fs.writeFile('./src/environments/environment.ts',
`// This file was autogenerated by build-env.js
export const environment = {
  production: false,
  apiUrl: '${process.env['API_URL']}',
  cognitoParams: {
    cognitoLoginUrl:'${process.env['COGNITO_AUTH_URL']}/login',
    cognitoLogoutUrl:'${process.env['COGNITO_AUTH_URL']}/logout',
    cognitoClientId: '${process.env['COGNITO_CLIENT_ID']}',
    cognitoResponseType: 'token',
    cognitoScope: 'openid+profile+aws.cognito.signin.user.admin',
    cognitoRedirectUri: '${process.env['CLIENT_UI_URL']}'
  }
};`,
(err) => {
  if (err) throw err;
  console.log('environment.ts file successfully created');
});
